services:
  francois:
    build: .
    volumes:
      - ./francois:/francois
    environment:
      - DJANGO_ENV=development
    ports:
      - 8000:8000
  
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - francois
