services:
  francois:
    build: .
    volumes:
      - ./francois:/francois
    environment:
      - DJANGO_ENV=development
    ports:
      - 8000:8000
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000